// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6.Models.AddMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("addMovies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 1,
                            Director = "Tony Scott",
                            Edited = false,
                            Rating = "PG",
                            Title = "Top Gun",
                            Year = "1986"
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 2,
                            Director = "David Mickey Evans",
                            Edited = false,
                            Rating = "PG",
                            Title = "The Sandlot",
                            Year = "1993"
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 7,
                            Director = "Various",
                            Edited = false,
                            Rating = "PG",
                            Title = "The Office",
                            Year = "2005-2013"
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 2,
                            Director = "Dennis Dugan",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Grown Ups",
                            Year = "2010"
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 1,
                            Director = "Sam Raimi",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Spider-Man",
                            Year = "2002"
                        });
                });

            modelBuilder.Entity("Mission6.Models.MovieCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("movieCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action/Adventure"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Horror/Suspense"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Miscellaneous"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Television"
                        },
                        new
                        {
                            Id = 8,
                            Name = "VHS"
                        });
                });

            modelBuilder.Entity("Mission6.Models.AddMovie", b =>
                {
                    b.HasOne("Mission6.Models.MovieCategories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
